# run: conda env create --file environment.yaml
name: diskfit
channels:
  - conda-forge
  - defaults
dependencies:
  - python<3.12
  - numpy<1.24
  - setuptools<74
  - pip
  - scipy
  - matplotlib
  - emcee
  - corner
  - astropy
  - jupyter
